export {default as Hero} from './Hero.tsx'
export {default as QrMain} from './alisher/qr-main.tsx'
export {default as Server} from './omadbek/Server.tsx'
export {default as Mobile} from './omadbek/mobile.tsx'
export {default as WebSayt} from './omadbek/WebSayt.tsx'