export {default as QrMain} from './alisher/qr-main.tsx'
export {default as PurposeProject} from './alisher/purpose-project.tsx'
export {default as MainComponents} from './alisher/main-components.tsx'
export {default as QrCreate} from './alisher/qr-create.tsx'
export {default as PaymentProcess} from './alisher/payment-process.tsx'
export {default as TransactionManagement} from './alisher/transaction-management.tsx'
export {default as NotificationsNotices} from './alisher/notifications-notices.tsx'
export {default as ReportsAnalysis} from './alisher/reports-analysis.tsx'
export {default as SubscriptionPayments} from './alisher/subscription-payments.tsx'


export {default as Server} from './omadbek/Server.tsx'
export {default as Mobile} from './omadbek/mobile.tsx'
export {default as WebSayt} from './omadbek/WebSayt.tsx'
export {default as XavfSizlik} from './omadbek/xavfsizlik.tsx'
export {default as SuniyIntelekt} from './omadbek/suniyIntelekt.tsx'
export {default as Lenguage} from './omadbek/Lenguage.tsx'
export {default as TelegramBot} from './omadbek/TelegramBot.tsx'
export {default as Quvvatlash} from './omadbek/quvvatlash.tsx'
